{% set version = "1.0-6" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-distillery
  version: {{ version|replace("-", "_") }}

source:
  fn: distillery_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/distillery_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/distillery/distillery_{{ version }}.tar.gz
  sha256: 4910e2952f767c1062d7cbe648c90a97009e2b3da316c6b33f6d022cd38b23d6

build:
  noarch: generic
  number: 0
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('distillery')"  # [not win]
    - "\"%R%\" -e \"library('distillery')\""  # [win]
    - conda inspect linkages -p $PREFIX r-distillery  # [not win]
    - conda inspect objects -p $PREFIX r-distillery  # [osx]

about:
  home: http://www.ral.ucar.edu/staff/ericg
  license: GPL (>= 2)
  summary: Some very simple method functions for confidence interval calculation, bootstrap resampling,
    and to distill pertinent information from a potentially complex object; primarily
    used in common with packages extRemes and SpatialVx.
  license_family: GPL3

extra:
  recipe-maintainers:
    - dpryan79
    - jsignell
