travis:
  secure:
    BINSTAR_TOKEN: KxDfZVzO1paYysp2si1tnjV98a8xoiZS3ePywenykC1aq06+sbIZh7+tqPGX+Zk08TJC9sLJoMv/W6Pc5Ci/WvSYLV/nBbJCzLZEsd4/dA92I/nStxA3gDYo39xOrdgGRgamEjXK3cMVnNtIg6MZ8BZX6hlwSCSlpW3Xy7MMXOogce7ZViHQgQ7dg5TALCQG7JlJx7l+cFMlaywavZYOhQyvcS8JBUECJ8+s9lRg9avlvYG2f1s7ugHdVWZNpeucPTDWgfnX24hxXtOw8JoD+RKg60daaxV55ESzUDtsH0/w6+UsWf5qdPb5a4oURnFsUIrW3h7KjQeMHfz4gbTFFZ1u7OQ/xoHYvbxjIW5umhRNEtSeZ5NA5TA/yf5HdPXrx7CGd9kzQSrKbdA8LkSRFCak4J896PDWQmA9uv/2+3HoWetmRrQdixZaBl6CuMued0O0RKOokNgqTTfcp1yOLuCAaQLRgRDMyk0gOKnIOjLgyAiaR7wqajihNuxOcnSdjyApiLWRWguvHl+hDy8A8/DMIq97FCBxN02nErmVY7sLUjC3q0FWCLc05zChJK44kwerS8Y9b/1cvm4Ky06lMxgpgmYNtVjleIeexwsY4/zskIIGMNoQkLZd8hHHo9DeAUGb80aSiWgX9B3Xzfvene654Vri4npKnqtloDRLmos=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
