travis:
  secure:
    BINSTAR_TOKEN: fBTlxDM2ZtpGqjQkxUT7qoNV7Ele9fvnKem1rZdLbdYFXBS+dklduWXcZn+LrYNpMaq+PkqcQ3WIqblv+NvG7C215siZ3SxapLh0sBXmlNsqxU4puvyU2kTYyd3puacE+xMFWc2xChlkfVfu8cYCaJ3kU+mPTf32ZTmJkV7qFQHGaKUtzOe0XtHmDAhlYLjjmxHxGnyHx3COzbV7MZWzTMFFWVxQAdk6mhosrqoiTFO+/VXI+JPG6C+KnYeFuKsxcqxY3CwqOvZJLjkKkaTA+IfCfLAoAp35FNbsUr0kxzfeiHxJFdC4y8Li1IEucr5ThqSb0OOfV0HvhkG7GQvVZ7BRkUE5jWWgQVzpbDPKIGJoZbzQwEpRHr10NUx+mZImlc0Iy+xU9SmVfRHKhXvid8tjhcW2zC6z8QKXcI8Z001O1bqbLsxOxKc7sD9KAwm7httbUSC6pVSkWWvRTP6OPaAsNgwFG2fUwPLWaXLK8O5G4cNIp7hN7OpsMYpqH854RW1W/8iKAmykAHP9MGMFRe4qD8FKreOEzt8NwFsBqFs/4vKehMJWrOOFl1aPWlYpk6tA9Td0yrE6XrmW36UMRmkp48pHvGnRF3MTEzlCiKPN/dXtCd1JRJ5MYyAfh2TJcbdEkpwtRy3Y/wROwiY3lELnde7SA6Z4s9AKcO8Jpt4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
