appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: ZP/r5gYZqTy+EpAadl30d2EnLizjLzdl2rISRjyBqVry/+by19xTMoIX89AtReRPSSjJYfFP73Im9hXF4G21QS409zSjKkAy6amh9vI/32sxXiqebMw1/AOsrnTOjha4gpOXNsdVak7JXf3isHtCQu5ncTn5Z3soZkA8aGdi5OLkUgQzr13SRa7D8Ey1OdslaR1Dy0dhh98nIoLudri91DxgLbrwt56iwocy9rsymtXRkXa4dxo6fuUSCF8Nv05uufbBvX0hcJBJRGWgZJDVZubW6yLHAB8vWsYFf6m5HdKrHg9ARgoobdsg993I9Ep/OSeJCglmOfM2EFPq/ZFnY6DtIg6ht32QY8DN441tD2MEvXfMtsVcpACgBBI4kehDJsL79VBINrZIkXllpof1YmdGTMyXVkP3n5wVtL0HgkQZkMGUhIi2rAYreKQ1b301cqAHGQ+lk3CFAu2uAcsD+4qMt/ehRzGoSt1CEcXHdNvzO+CX/L9FWfRhO1VwREeod7w58n3bCZqZ9M7bKw58ucYjS8Q/2AyfY/ylHVHza/fqsguZihOncJmnbITCAOXYT+q0qDvnv5iiBMfReJKCszJtyc0gHEU+tXJQj2Dz9ZY2pxUIx/tbL9N/AoDdXpF+v5AhC1JkKcjJdZkJkZPfb9A91/1wGnjFmNDGJxxOMnM=}
